- hosts: "{{HOSTS}}"
  become: true

  tasks:
    - name: "set the sysctl net.ipv4.tcp_challenge_ack_limit = 100"
      sysctl: name=net.ipv4.tcp_challenge_ack_limit value=100

    - name: switch default kernels
      shell: /sbin/grubby --set-default=/boot/vmlinuz-3.10.0-123.el7.x86_64

    - block:
        - name: reboot the machine
          shell: sleep 2 && shutdown -r now "Ansible triggered reboot"
          async: 1
          poll: 0

        - name: waiting for server to come back
          wait_for_connection: delay=30 timeout=300
          become: false

    - name: remove latest kernel
      shell: yum erase -y kernel-3.10.0-327.28.3.el7

    - name: set the default boot kernel back to =1
      shell: /sbin/grubby --set-default-index=1
